/**
 * Wrap `src/client/index.js` into the host's module-loader bundle format.
 *
 * The host loads a plugin's browser half as a classic script that registers a
 * CommonJS factory:
 *
 *   window.__ModuleLoader__.load({ id: "<package>", factory: (require) => { … } })
 *
 * The card is authored as plain CJS against that contract, so building it is a
 * wrap — not a bundler run. That keeps the plugin dependency-free: there is no
 * build toolchain to install and no JSX transform to drift.
 *
 *   node scripts/build-client.mjs
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const source = path.join(root, 'src', 'client', 'index.js')
const target = path.join(root, 'lib', 'client.js')

const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))
const body = fs.readFileSync(source, 'utf8')

// The factory body must not already define `module`/`exports`; the wrapper owns them.
if (/^\s*(var|let|const)\s+module\s*=/m.test(body) || /^\s*(var|let|const)\s+exports\s*=/m.test(body)) {
  throw new Error('src/client/index.js must not declare its own module/exports; the wrapper provides them')
}

const bundle = [
  '// Generated by scripts/build-client.mjs — edit src/client/index.js instead.',
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pkg.name)},`,
  '  factory: (require) => {',
  '    var module = { exports: {} };',
  '    var exports = module.exports;',
  body.replace(/^/gm, '    ').replace(/^\s+$/gm, ''),
  '    return module.exports;',
  '  },',
  '});',
  '',
].join('\n')

fs.mkdirSync(path.dirname(target), { recursive: true })
fs.writeFileSync(target, bundle, 'utf8')

console.log(`wrote ${path.relative(root, target)} (${bundle.length} bytes)`)
